server:
  port: 8080

spring:
  application:
    name: Categorizador
  datasource:
    url: jdbc:postgresql://localhost:5432/categorizador
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
